from ..transfer import Transfer
from ...utils import rest
from ...utils.api import from_api_json
from ...utils.checks import check_datetime
from ...utils.resource import Resource


class TransferLog(Resource):
    """Description: TransferLog object

    Every time a Transfer entity is modified, a correspondent TransferLog
    is generated for the entity. This log is never generated by the
    user.

    Attributes:
        transfer [Transfer]: Transfer entity to which the log refers to.
        id [string, default None]: unique id returned when log is created. ex: "5656565656565656"
        errors [list]: list of errors in case log was generated by webhook event
        type [string, default None]: type of the Transfer event which triggered log creation. ex: "processing" or "success"
        created [datetime.datetime, default None]: creation datetime for the transfer. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, created, type, errors, transfer):
        Resource.__init__(self, id=id)

        self.created = check_datetime(created)
        self.type = type
        self.errors = errors
        self.transfer = from_api_json(Transfer, transfer)


def get(id, user=None):
    return rest.get_id(resource=TransferLog, id=id, user=user)


def query(limit=None, transfer_ids=None, events=None, user=None):
    return rest.get_list(resource=TransferLog, limit=limit, user=user, events=events, transfer_ids=transfer_ids)
