from starkcore.utils.api import from_api_json
from starkcore.utils.resource import Resource
from starkcore.utils.checks import check_datetime, check_date
from ...utils import rest
from ..__acquiringcard import _resource as _acquiring_card_resource


class Log(Resource):
    """# acquiringcard.Log object
    Every time an AcquiringCard entity is updated, a corresponding acquiringcard.Log is generated for the entity.
    This log is never generated by the user, but it can be retrieved to check additional information
    about the AcquiringCard.
    ## Attributes:
    - id [string]: unique id returned when the log is created. ex: "5656565656565656"
    - card [AcquiringCard]: AcquiringCard entity to which the log refers to.
    - type [string]: type of the AcquiringCard event which triggered the log creation. ex: "blocked", "canceled", "created", "expired", "unblocked", "updated"
    - created [datetime.datetime]: creation datetime for the log. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, card, type, created):
        Resource.__init__(self, id=id)

        self.card = from_api_json(_acquiring_card_resource, card)
        self.type = type
        self.created = check_datetime(created)


_resource = {"class": Log, "name": "AcquiringCardLog"}


def get(id, user=None):
    """# Retrieve a specific acquiringcard.Log
    Receive a single acquiringcard.Log object previously created by the Stark Bank API by its id
    ## Parameters (required):
    - id [string]: object unique id. ex: "5656565656565656"
    ## Parameters (optional):
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkbank.user was set before function call.
    ## Return:
    - acquiringcard.Log object with updated attributes
    """
    return rest.get_id(resource=_resource, id=id, user=user)


def query(ids=None, card_ids=None, types=None, after=None, before=None, limit=None, user=None):
    """# Retrieve acquiringcard.Log
    Receive a generator of acquiringcard.Log objects previously created in the Stark Bank API
    ## Parameters (optional):
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
    - after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["blocked", "canceled", "created", "expired", "unblocked", "updated"]
    - card_ids [list of strings, default None]: list of AcquiringCard ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkbank.user was set before function call.
    ## Return:
    - generator of acquiringcard.Log objects with updated attributes
    """
    return rest.get_stream(
        resource=_resource,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        card_ids=card_ids,
        user=user,
    )


def page(cursor=None, ids=None, limit=None, after=None, before=None, types=None, card_ids=None, user=None):
    """# Retrieve paged acquiringcard.Log
    Receive a list of up to 100 acquiringcard.Log objects previously created in the Stark Bank API and the cursor to the next page.
    Use this function instead of query if you want to manually page your requests.
    ## Parameters (optional):
    - cursor [string, default None]: cursor returned on the previous page function call
    - ids [list of strings, default None]: list of ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
    - limit [integer, default 100]: maximum number of objects to be retrieved. It must be an integer between 1 and 100. ex: 50
    - after [datetime.date or string, default None] date filter for objects created only after specified date. ex: datetime.date(2020, 3, 10)
    - before [datetime.date or string, default None] date filter for objects created only before specified date. ex: datetime.date(2020, 3, 10)
    - types [list of strings, default None]: filter for log event types. ex: ["blocked", "canceled", "created", "expired", "unblocked", "updated"]
    - card_ids [list of strings, default None]: list of AcquiringCard ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - user [Organization/Project object, default None]: Organization or Project object. Not necessary if starkbank.user was set before function call.
    ## Return:
    - list of acquiringcard.Log objects with updated attributes
    - cursor to retrieve the next page of acquiringcard.Log objects
    """
    return rest.get_page(
        resource=_resource,
        cursor=cursor,
        ids=ids,
        limit=limit,
        after=check_date(after),
        before=check_date(before),
        types=types,
        card_ids=card_ids,
        user=user,
    )
