from ....utils import rest
from ....utils.api import from_api_json
from ....utils.checks import check_datetime
from ....utils.resource import Resource
from ..utilityPayment import UtilityPayment


class UtilityPaymentLog(Resource):
    """Description: UtilityPaymentLog object

    Every time a UtilityPayment entity is modified, a correspondent UtilityPaymentLog
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the UtilityPayment.

    Attributes:
        payment [UtilityPayment]: UtilityPayment entity to which the log refers to.
        id [string, default None]: unique id returned when log is created. ex: "5656565656565656"
        errors [list]: list of errors in case log was generated by webhook event
        type [string, default None]: type of the UtilityPayment event which triggered log creation. ex: "registered" or "paid"
        created [datetime.datetime, default None]: creation datetime for the payment. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, created, type, errors, payment):
        Resource.__init__(self, id=id)

        self.created = check_datetime(created)
        self.type = type
        self.errors = errors
        self.payment = from_api_json(UtilityPayment, payment)


def get(id, user=None):
    """Retrieve a single UtilityPaymentLog

    Receive a single UtilityPaymentLog object previously created by the Stark Bank API by passing its id

    Parameters (required):
        id [string]: object unique id. ex: "5656565656565656"
    Parameters (optional):
        user [Project object]: optional Project object. Not necessary if starkbank.user was set before function call
    Return
        UtilityPaymentLog object with updated return-only attributes
    """
    return rest.get_id(resource=UtilityPaymentLog, id=id, user=user)


def query(limit=None, payment_ids=None, events=None, user=None):
    """Retrieve UtilityPaymentLogs

    Receive a generator of UtilityPaymentLog objects previously created in the Stark Bank API

    Parameters (optional):
        limit [integer, default None]: optional number of objects to be retrieved. Unlimited if None. ex: 35
        payment_ids [list of strings, default None]: optional list of ids to filter selected objects. ex: ["5656565656565656", "4545454545454545"]
        events [string, default None]: optional filter for events of objects retrieved. ex: "paid" or "registered"
        user [Project object, default None]: optional Project object. Not necessary if starkbank.user was set before function call
    Return
        list of UtilityPaymentLog objects with updated return-only attributes
    """
    return rest.get_list(resource=UtilityPaymentLog, limit=limit, user=user, events=events, payment_ids=payment_ids)
