from starkbank.utils import rest
from starkbank.utils.checks import check_datetime, check_date
from starkbank.boleto.boleto import Boleto
from starkbank.utils.api import from_api_json
from starkbank.utils.resource import Resource


class BoletoLog(Resource):
    """BoletoLog object

    Every time a Boleto entity is updated, a corresponding BoletoLog
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the Boleto.

    Attributes:
        id [string]: unique id returned when the log is created. ex: "5656565656565656"
        boleto [Boleto]: Boleto entity to which the log refers to.
        errors [list of strings]: list of errors linked to this Boleto event
        type [string]: type of the Boleto event which triggered the log creation. ex: "registered" or "paid"
        created [datetime.datetime]: creation datetime for the boleto. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, created, type, errors, boleto):
        Resource.__init__(self, id=id)

        self.created = check_datetime(created)
        self.type = type
        self.errors = errors
        self.boleto = from_api_json(Boleto, boleto)


def get(id, user=None):
    """Retrieve a specific BoletoLog

    Receive a single BoletoLog object previously created by the Stark Bank API by passing its id

    Parameters (required):
        id [string]: object unique id. ex: "5656565656565656"
    Parameters (optional):
        user [Project object]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        BoletoLog object with updated attributes
    """
    return rest.get_id(resource=BoletoLog, id=id, user=user)


def query(limit=None, boleto_ids=None, types=None, after=None, before=None, user=None):
    """Retrieve BoletoLogs

    Receive a generator of BoletoLog objects previously created in the Stark Bank API

    Parameters (optional):
        limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
        boleto_ids [list of strings, default None]: list of Boleto ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
        types [list of strings, default None]: filter for log event types. ex: "paid" or "registered"
        user [Project object, default None]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        list of BoletoLog objects with updated attributes
    """
    return rest.get_list(resource=BoletoLog, limit=limit, user=user, types=types, boleto_ids=boleto_ids, after=check_date(after), before=check_date(before))
