from ..utils import rest
from ..utils.resource import Resource
from ..utils.checks import check_datetime


class Balance(Resource):
    """Description: Balance object

    The Balance object displays the current balance of the workspace,
    which is the result of the sum of all transactions within this
    workspace. The balance is never generated by the user, but it
    can be retrieved to see the information available.

    Attributes (return-only):
        id [string, default None]: unique id returned when Boleto is created. ex: "5656565656565656"
        amount [integer, default None]: current balance amount of the workspace in cents. ex: 200 (= R$ 2.00)
        status [string, default None]: currency of the current workspace. Expect others to be added eventually. ex: "BRL"
        updated [datetime.datetime, default None]: update datetime for the balance. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, amount, currency, updated, id):
        Resource.__init__(self, id=id)

        self.amount = amount
        self.currency = currency
        self.updated = check_datetime(updated)


def get(user=None):
    """Retrieve first Balance object

    Receive the first Balance object available in the Stark Bank API

    Parameters (optional):
        user [Project object]: optional Project object. Not necessary if starkbank.user was set before function call
    """
    return next(rest.get_list(resource=Balance, user=user))
