from ....utils import rest
from ....utils.api import from_api_json
from ....utils.checks import check_datetime
from ....utils.resource import Resource
from ..boletoPayment import BoletoPayment


class BoletoPaymentLog(Resource):
    """BoletoPaymentLog object

    Every time a BoletoPayment entity is modified, a corresponding BoletoPaymentLog
    is generated for the entity. This log is never generated by the
    user, but it can be retrieved to check additional information
    on the BoletoPayment.

    Attributes:
        id [string, default None]: unique id returned when the log is created. ex: "5656565656565656"
        payment [BoletoPayment]: BoletoPayment entity to which the log refers to.
        errors [list of strings]: list of errors linked to this BoletoPayment event.
        type [string, default None]: type of the BoletoPayment event which triggered the log creation. ex: "registered" or "paid"
        created [datetime.datetime, default None]: creation datetime for the payment. ex: datetime.datetime(2020, 3, 10, 10, 30, 0, 0)
    """

    def __init__(self, id, created, type, errors, payment):
        Resource.__init__(self, id=id)

        self.created = check_datetime(created)
        self.type = type
        self.errors = errors
        self.payment = from_api_json(BoletoPayment, payment)


def get(id, user=None):
    """Retrieve a specific BoletoPaymentLog

    Receive a single BoletoPaymentLog object previously created by the Stark Bank API by passing its id

    Parameters (required):
        id [string]: object unique id. ex: "5656565656565656"
    Parameters (optional):
        user [Project object]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        BoletoPaymentLog object with updated attributes
    """
    return rest.get_id(resource=BoletoPaymentLog, id=id, user=user)


def query(limit=None, payment_ids=None, types=None, user=None):
    """Retrieve BoletoPaymentLogs

    Receive a generator of BoletoPaymentLog objects previously created in the Stark Bank API

    Parameters (optional):
        limit [integer, default None]: maximum number of objects to be retrieved. Unlimited if None. ex: 35
        payment_ids [list of strings, default None]: list of BoletoPayment ids to filter retrieved objects. ex: ["5656565656565656", "4545454545454545"]
        types [list of strings, default None]: filter retrieved objects by event types. ex: "paid" or "registered"
        user [Project object, default None]: Project object. Not necessary if starkbank.user was set before function call
    Return:
        list of BoletoPaymentLog objects with updated attributes
    """
    return rest.get_list(resource=BoletoPaymentLog, limit=limit, user=user, types=types, payment_ids=payment_ids)
